FROM centos
MAINTAINER yuriko
RUN     yum -y update && \
	yum -y install python-setuptools python-devel gcc && \
        yum clean all && easy_install pip && \
	pip install rainbowstream==1.4.0

COPY	.rainbow_oauth /root/.rainbow_oauth
CMD	/usr/bin/rainbowstream
